import fs from 'node:fs/promises';
import path from 'node:path';

async function copyDir(src, dest) {
  await fs.mkdir(dest, { recursive: true });
  const entries = await fs.readdir(src, { withFileTypes: true });
  for (const e of entries) {
    const s = path.join(src, e.name);
    const d = path.join(dest, e.name);
    if (e.isDirectory()) await copyDir(s, d);
    else await fs.copyFile(s, d);
  }
}

async function main() {
  await fs.rm('dist', { recursive: true, force: true });
  await copyDir('site', 'dist');
  await fs.mkdir('dist/data', { recursive: true });
  // data/lotteries.json will be generated by the scrape step; workflow copies it after.
  console.log('Built dist/ from site/');
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
